### ISSUE TITLE
Conflict with mobx-react-devtools

### ISSUE THREAD

**Issue by PawelGIX** [andykog/mobx-devtools#10]
Is this a bug? Can I have a problem with my configuration?

TypeError: Cannot set property 'time' of undefined at Object.push (chrome-extension://pfgnfdagidkfgccljigdamigbcnndkod/backend.js:1492:24) at Array.<anonymous> (chrome-extension://pfgnfdagidkfgccljigdamigbcnndkod/backend.js:1403:30) at spyReport (https://unpkg.com/mobx@3.2.2/lib/mobx.umd.js:177:21) at spyReportEnd (https://unpkg.com/mobx@3.2.2/lib/mobx.umd.js:186:9) at Reaction.track (https://unpkg.com/mobx@3.2.2/lib/mobx.umd.js:2995:13) at Reaction.onInvalidate (https://unpkg.com/mobx@3.2.2/lib/mobx.umd.js:1159:14) at Reaction.runReaction (https://unpkg.com/mobx@3.2.2/lib/mobx.umd.js:2960:22) at runReactionsHelper (https://unpkg.com/mobx@3.2.2/lib/mobx.umd.js:3088:35) at reactionScheduler (https://unpkg.com/mobx@3.2.2/lib/mobx.umd.js:3066:47) at https://unpkg.com/mobx@3.2.2/lib/mobx.umd.js:3095:71

![image](https://user-images.githubusercontent.com/391153/32503844-8ea6b98a-c3de-11e7-86dc-44ff452ec14a.png)
![image](https://user-images.githubusercontent.com/391153/32504041-1db61fd0-c3df-11e7-9a2a-83cbac705dca.png)

**Comment by andykog** [comment]
@PawelGIX, seems that mobx spy emitted more `spyReportEnd` events than `spyReportStart` events. Do you see that error more or less regularly? What version of MobX are you using?

**Comment by PawelGIX** [comment]
Resolved. There was conflict with https://unpkg.com/mobx-react-devtools@4.2.11 loaded in script tag ;]

**Comment by andykog** [comment]
@PawelGIX, thanks for figuring that out. It shouldn't conflict with mobx-react-devtools though, will take a look tomorrow.

**Comment by andykog** [comment]
Can't reproduce, but added a safety check, so that shouldn't happen again
