### ISSUE TITLE
Draft new release please

### ISSUE THREAD

**Issue by lancemccluskey** [andykog/mobx-devtools#100]
Im trying to use `mobx-devtools-mst` with typescript but having issues. I see @epodgaetskiy  merged the fix back in December the day after the last release when out. Can we draft a new release?

**Comment by lancemccluskey** [comment]
@andykog @epodgaetskiy @realityforge @mweststrate @AlexKom9 @MichalBures @kuasha420 For visibility. Apologies for tagging you if you dont have permission to draft releases.

**Comment by epodgaetskiy** [comment]
@lancemccluskey There isn't bug in version `mobx-devtools-mst: 0.9.30`, look [example](https://codesandbox.io/s/inspiring-firefly-tcj5s?file=/src/App.tsx).
Can you provide your example with an error?

**Comment by MichalBures** [comment]
@lancemccluskey Please don't tag random contributors and demand they do stuff for you.

**Comment by lancemccluskey** [comment]
@MichalBures Apologies, I didnt mean to offend. I only tagged multiple contributors because I noticed multiple issues (some from years ago) that never received any replies and I didnt want mine to get "lost in the wind". I get thats annoying though and wont do it again.

**Comment by lancemccluskey** [comment]
@epodgaetskiy im working on an existing application and we have many nested mst nodes. Im not sure what the issue is but after looking at your sandbox im thinking its an issue with our models. Thanks for taking the time to respond. I appreciate it
