### ISSUE TITLE
Update to Manifest v3 (at least for Chrome)

### ISSUE THREAD

**Issue by coolsoftwaretyler** [andykog/mobx-devtools#120]
This browser extension is on the old browser extension manifest version, v2.

We should [upgrade to v3 for chrome](https://developer.chrome.com/docs/extensions/develop/migrate) and [evaluate if it makes sense to do the same for Firefox](https://blog.mozilla.org/addons/2024/03/13/manifest-v3-manifest-v2-march-2024-update/) to get things up to date.

**Comment by andykog** [comment]
Indeed, there’s a warning in Chrome Web Store that they will stop supporting manifest v2 soon

**Comment by coolsoftwaretyler** [comment]
I'll get started on this today.

**Comment by coolsoftwaretyler** [comment]
This'll be a bigger lift. Here is a checklist from Chrome: https://developer.chrome.com/docs/extensions/develop/migrate/checklist

After some initial exploration, I think the biggest items will be: 

1. Changing the backend to be a service worker (may require some new patterns to connect to our backend)
2. Removing the unsafe evaluations and inlined scripts
3. Changing some of the UI to more modern patterns (like using a side panel instead of a separate window)

**Comment by coolsoftwaretyler** [comment]
Closed in https://github.com/mobxjs/mobx-devtools/pull/129!
