### ISSUE TITLE
chrome.extension.onMessage doesn't exist in FF58. Maybe chrome.runtime.onMessage?

### ISSUE THREAD

**Issue by nspaeth** [andykog/mobx-devtools#14]
I couldn't get the extension to connect to my stores so I tried opening it in the extension debugger to see if there were any errors.

This one might explain my issue?
`TypeError: chrome.extension.onMessage is undefined`

See https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/extension and https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime

**Comment by andykog** [comment]
@nspaeth, thanks for reporting and locating the problem!
Fixed in v0.9.11. + fixed several layout problems in firefox.
