### ISSUE TITLE
anonymous actions/computed

### ISSUE THREAD

**Issue by janat08** [andykog/mobx-devtools#18]
``next: action((i)=>{`` or ``queryPeriods: mobx.computed(function() {`` with name parameter will show up as anonymous or unnamed (action indeed being unnamed).

**Comment by andykog** [comment]
Sorry, I don't understand your problem/proposition

**Comment by janat08** [comment]
In "changes" tab of extension computed or actions that are declared in the above format will show up without any identifying information.

**Comment by andykog** [comment]
Yep, that's because you are using anonymous function. There are 2 options on how to give mobx a clue about actions' names:

1. Use named function:
```js
action(function myActionName() {...});
```
2. Use [mobx api](https://mobx.js.org/refguide/action.html) to provide the name:
```js
action('myActionName', () => {...})

// or

class {
  @action('myActionName') someAction () {...}
}
```
