### ISSUE TITLE
MST/Changes tab not working

### ISSUE THREAD

**Issue by ianschmitz** [andykog/mobx-devtools#28]
The MST/Changes tab seemed to have stopped working on the most recent version of the MobX dev tools for Chrome.

I'm using:
- mobx@4.1.0
- mobx-react@5.0.0
- mobx-state-tree@2.0.2
- mobx-devtools-mst@0.9.14
- MobX dev tools extension for Chrome@0.9.16

When i open the `MST` tab i see: 
![image](https://user-images.githubusercontent.com/6355370/37992850-b6260924-31c1-11e8-9c4b-e2ac6ce1590d.png)

And the `Changes` tab does not record anything when actions are performed on the MST store.

**Comment by adrianObel** [comment]
+1 Latest version isn't working for me either.

**Comment by naivefun** [comment]
same here ...

**Comment by andykog** [comment]
Fixed in 0.9.17
I should have written tests for this extension long ago.
