### ISSUE TITLE
Cannot read property 'observing' of undefined

### ISSUE THREAD

**Issue by Leotw** [andykog/mobx-devtools#32]
I'm using MobX Developer Tools in Chrome extensions. The Chrome console shows some errors:

```
backend.js:5095 Uncaught TypeError: Cannot read property 'observing' of undefined
    at getDepsTree (backend.js:5095)
    at exports.default (backend.js:5106)
    at backend.js:4929
    at backend.js:1097
    at Array.forEach (<anonymous>)
    at backend.js:1096
    at Array.forEach (<anonymous>)
    at Bridge.$handleMessage (backend.js:1092)
    at listener (backend.js:4133)
```

Platform: Chrome 67.0.3396.87
mobx-react: 5.2.3
mobx: 5.0.2

**Comment by andykog** [comment]
Thanks for the report, `mobx-devtools` are not compatible with MobX@5 yet, I'm going to fix that tomorrow

**Comment by andykog** [comment]
Should be fixed in v0.9.18

**Comment by Leotw** [comment]
😊 Thanks for fixing this problem. It needs to add the developer tools in Chrome extensions again to work.

**Comment by Leotw** [comment]
Well...there is another point. I created a stateless component named Detail by this way:

```
import React from 'react';
import { observer } from 'mobx-react';

const Detail = observer((props) => {
  return (
    <div className="Detail">
      <a onClick={props.getAppStore}>Call</a>
    </div>
  )
})
export default Detail;
```

I import `Detail` in `App`: 

```
@observer
class App extends Component {
  render() {
    return (
      <div className="App">
        <Detail/>  
      </div>
    );
  }
}
```

I switch the component tab,  the `mobx-devtools` shows in this way:

![image](https://user-images.githubusercontent.com/12053096/41508609-0ee7667c-727a-11e8-83a1-137a92a34d9d.png)

Is it correct? `Detail`lost name.
