### ISSUE TITLE
Props not displayed when on component view

### ISSUE THREAD

**Issue by jeserkin** [andykog/mobx-devtools#34]
When I select component in MobX view, then in the right sidebar everything is mentioned, besides `props`. For some reason, since recent times, they are not present there anymore.

![image](https://user-images.githubusercontent.com/183512/42319021-63787450-8059-11e8-8618-fe9cb7917f31.png)

Like for example on link provided by MobX documentation https://codesandbox.io/s/v3v0my2370
one can clearly see 

![image](https://user-images.githubusercontent.com/183512/42319374-7624078a-805a-11e8-80fb-05dbd65609d9.png)

**Comment by andykog** [comment]
Thanks for reporting, was broken after https://github.com/mobxjs/mobx-react/pull/496 will be fixed in next version release
