### ISSUE TITLE
"> mobx-devtools-mst@0.9.18" has incorrect peer dependency "mobx@^2.2.0 || ^3.0.0".

### ISSUE THREAD

**Issue by joanjoantan** [andykog/mobx-devtools#36]
With mobx (4):

```
$ yarn upgrade mobx-devtools-mst
warning " > mobx-devtools-mst@0.9.18" has incorrect peer dependency "mobx@^2.2.0 || ^3.0.0".
[5/5] 📃  Rebuilding all packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ mobx-devtools-mst@0.9.18
info All dependencies
└─ mobx-devtools-mst@0.9.18
✨  Done in 6.33s.
```

**Comment by Amareis** [comment]
+1, and there is no state of the tree in right panel
![image](https://user-images.githubusercontent.com/4806617/45962499-6a5e4800-c03a-11e8-8346-ad7281ae4830.png)

**Comment by Amareis** [comment]
Oh, there is no state because actions called too early when dev tools are not connected even.

**Comment by tdkn** [comment]
@andykog
There is no any update for MobX 5? :sweat_smile:
https://github.com/mobxjs/mobx-devtools/blob/81126c3c9fd5a39cba48407d7ae28a94e2cf39d8/packages/mobx-devtools-mst/package.json#L26

**Comment by agos** [comment]
0.9.21 has yet another issue, a missing pipe means that the peer dependency is not matching
