### ISSUE TITLE
Missing component and perfomance tabs

### ISSUE THREAD

**Issue by khomyakov42** [andykog/mobx-devtools#60]
![Снимок экрана от 2019-09-17 22-31-46](https://user-images.githubusercontent.com/866005/65041848-fb8ca400-d99a-11e9-9bca-345dd1b83d57.png)
I do not see component and perfomance tabs in the developer panel
"mobx-devtools-mst": "^0.9.21",
"mobx": "5.13.0",
"mobx-react": "^6.1.1",
"mobx-state-tree": "3.14.1",

**Comment by anikethsaha** [comment]
This is a known issue which is already opened https://github.com/mobxjs/mobx-devtools/issues/56
I guess as of now you can try downgrading the mobx and mobx-react until the fix comes out !

**Comment by epodgaetskiy** [comment]
Hi!
Prefer use React Devtools extension for components tree and performance [discuss](https://github.com/mobxjs/mobx-devtools/issues/56#issuecomment-541896923)
