### ISSUE TITLE
TypeScript typing error in mobx-devtools-mst and quick fix

### ISSUE THREAD

**Issue by wjureczka** [andykog/mobx-devtools#91]
Hi, I found a bug in typings:

https://github.com/mobxjs/mobx-devtools/blob/master/packages/mobx-devtools-mst/index.d.ts#L1

I think this line should be: `export default (root: Object): Object => {return root;};`

**Comment by wjureczka** [comment]
Moreover the ambient context crashes, same as here: https://github.com/mobxjs/mobx-devtools/issues/88

**Comment by epodgaetskiy** [comment]
@wjureczka Check please with `mobx-devtools-mst@0.9.30`
